# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10
# terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms
require 'pry'

class EvenFib
  attr_accessor :max_value

  def initialize (max_value)
    @max_value = max_value
  end

  def fib_sum
    num1= 0
    num2= 1
    sum =1
    num_array = []

    while num2 < @max_value
      sum = num1 + num2
      even_num_array.push(sum) if sum % 2 == 0
      num1 = num2
      num2 = sum
    end
   even_num_array.reduce(:+)
  end
end
